### ISSUE TITLE
osx: Shared library collecting doesn't work

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/kcov#157]

**Comment by SimonKagstrom** [comment]
Yes, I haven't been looking at the OSX stuff in quite a while. I didn't realise this meant that Rust binaries doesn't work.

I suppose one should look at `SBTarget::AddModule`, but I'm no expert at the LLDB API.

**Comment by SimonKagstrom** [comment]
Fixed with cfdfbf9.

**Comment by andrewdavidmackenzie** [comment]
Nice, I'll look out for a new release with this fix to try it out!

**Comment by SimonKagstrom** [comment]
I've just released a version the other day, so it will be some time until the next release. I should say that it's quite lightly tested, but at least works in my tests.

**Comment by palfrey** [comment]
Just tried `cargo install cargo-kcov --git https://github.com/kennytm/cargo-kcov` on OS X and I'm still seeing `error: kcov cannot collect coverage on Windows or OS X`

**Comment by SimonKagstrom** [comment]
Well, that sounds like a bug in cargo. Kcov has supported osx for a while,
and shared libraries since recently. Windows is not on the table yet though!

**Comment by palfrey** [comment]
@SimonKagstrom Apologies! https://github.com/kennytm/cargo-kcov linked to this issue, and I wasn't paying enough attention. I've filed this over there.

**Comment by SimonKagstrom** [comment]
No need to apologise!

And to be fair: if rust requires the shared library stuff, it would have
been true until the last two weeks or so :-)

I also suspect rust hasn't been tried on osx yet, so bugs might lurk around.
