### ISSUE TITLE
Feature Request: Allow lines and lines ranges to be excluded

### ISSUE THREAD

**Issue by malbarbo** [SimonKagstrom/kcov#180]
`lcov` allows excluding lines and lines range adding marks in the code. See http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

It would be great if `kcov` had something like that.

I'm using `kcov` in Rust projects and some functions that could panic (but does not because of the invariants of the function) are never 100% covered. This also happens when [`unreachable!`](https://doc.rust-lang.org/stable/std/macro.unreachable.html) macro is used.

**Comment by kswmsw** [comment]
+1. It's much easier to maintain a target of 100%-coverage-with-explicit-exclusions than "high coverage" (which inevitably rots over time). By marking a particular range as not covered, rather than a percentage of the code, the developer and the reviewer have to think about what is and is not sensible to test, allowing pragmatic decisions.

A good start would be to implement `LCOV_EXCL_LINE`, `LCOV_EXCL_START`, and `LCOV_EXCL_STOP`. For compatibility we might as well use the same names, rather than inventing our own.

Lines marked with this (whether or not they are executed) don't count towards coverage (either for or against) - it's as if they are not in the program.

**Comment by SimonKagstrom** [comment]
I agree, good ideas.

Issue #175 implements part of this, but only for single lines. Having it work for ranges would be more useful, and using the same markers as lcov makes sense.


Best is probably to extend the filter handling (src/filter.cc) to also have a runLineFilters(file, line) callback and a class that checks for the LCOV markers and markers passed with --unreachable=

**Comment by SimonKagstrom** [comment]
Fixed with e620da4.

I'll keep the bug report open until I've added the ability to specify markers for start/end from the command line (i.e., in addition to the LCOV_EXCL_START/STOP which is there now).

**Comment by SimonKagstrom** [comment]
Fixed with c75e478.

The options are now named --exclude-line= and --exclude-region=.


The travis build fails with these fixes for some reason, will have to look into that.

**Comment by kswmsw** [comment]
Hi Simon - thanks for the speedy enhancement!

Unfortunately I can't seeem to get it to work. I'm using 2b1c0e511bfbd5f3754fa779eabbbab55d8860fb and I can't see any effect of the LCOV_EXCL_START / LCOV_EXCL_STOP lines:

```
$ cat -n hello.c 
     1	#include <stdio.h>
     2	#include <stdlib.h>
     3	
     4	int main(int argc, char* argv[]) {
     5	  if (argc == 99) {
     6	    // LCOV_EXCL_START
     7	    printf("Noooo...\n");
     8	    // LCOV_EXCL_STOP
     9	  }
    10	  printf("Hello world!\n");
    11	  exit(0);
    12	}
    13	
$ gcc -g hello.c 
$ kcov --version
kcov v33-25-g2b1c
$ kcov out a.out
Hello world!
$ cat index.json 
var data = {files:[
{"link":"a.out/index.html","title":"a.out","summary_name":"a.out","covered_class":"lineCov","covered":"80.0","covered_lines":"4","uncovered_lines":"1","total_lines" : "5"},
], merged_files:[]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "a.out", "date" : "2017-01-30 10:57:34", "instrumented" : 5, "covered" : 4,};
```

I was expecting 100% coverage, not 80%. The detailed HTML report shows lines 4, 5, 10, 11 are hit and line 7 is not. I've tried explicitly passing `--exclude-region` and that's not the problem; also I've tried using `LCOV_EXCL_LINE` on the offending line and that doesn't fix it either.

Unrelatedly, there's a missing newline in `kcov --help` before `--exclude-region`.

Any ideas what's happening here?

**Comment by SimonKagstrom** [comment]
Ah, sorry. I've only been testing with the bash "engine" (which is most convenient when writing automated tests).

The reason is that the elf parser only reports actual code lines, so the comment lines are never seen by the filter. Reopening until this is fixed.

**Comment by kswmsw** [comment]
Cool, thanks.

**Comment by SimonKagstrom** [comment]
Your example should now work after f7d1ae2, closing again when the automated tests have run.

**Comment by kswmsw** [comment]
Fantastic! That works! But merging isn't quite right. Using the same hello.c:
```
$ kcov --version
kcov v33-26-gf6d1
$ kcov first a.out
Hello world!
$ kcov second a.out
Hello world!
$ kcov --merge third first second
$ cat first/a.out/hello.c.3c6dbdb9.json 
var data = {lines:[
{"lineNum":"    1","line":"#include <stdio.h>"},
{"lineNum":"    2","line":"#include <stdlib.h>"},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"int main(int argc, char* argv[]) {","class":"lineCov","hits":"1","order":"2","possible_hits":"1",},
{"lineNum":"    5","line":"  if (argc == 99) {","class":"lineCov","hits":"1","order":"3","possible_hits":"1",},
{"lineNum":"    6","line":"    // LCOV_EXCL_START"},
{"lineNum":"    7","line":"    printf(\"Noooo...\\n\");"},
{"lineNum":"    8","line":"    // LCOV_EXCL_STOP"},
{"lineNum":"    9","line":"  }"},
{"lineNum":"   10","line":"  printf(\"Hello world!\\n\");","class":"lineCov","hits":"1","order":"4","possible_hits":"1",},
{"lineNum":"   11","line":"  exit(0);","class":"lineCov","hits":"2","order":"1","possible_hits":"2",},
{"lineNum":"   12","line":"}"},
{"lineNum":"   13","line":""},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "a.out", "date" : "2017-01-30 11:57:43", "instrumented" : 4, "covered" : 4,};
var merged_data = [];
$ cat third/kcov-merged/hello.c.3c6dbdb9.json 
var data = {lines:[
{"lineNum":"    1","line":"#include <stdio.h>"},
{"lineNum":"    2","line":"#include <stdlib.h>"},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"int main(int argc, char* argv[]) {","class":"lineCov","hits":"1","order":"4",},
{"lineNum":"    5","line":"  if (argc == 99) {","class":"lineCov","hits":"1","order":"3",},
{"lineNum":"    6","line":"    // LCOV_EXCL_START"},
{"lineNum":"    7","line":"    printf(\"Noooo...\\n\");","class":"lineNoCov","hits":"0",},
{"lineNum":"    8","line":"    // LCOV_EXCL_STOP"},
{"lineNum":"    9","line":"  }"},
{"lineNum":"   10","line":"  printf(\"Hello world!\\n\");","class":"lineCov","hits":"1","order":"2",},
{"lineNum":"   11","line":"  exit(0);","class":"lineCov","hits":"1","order":"1",},
{"lineNum":"   12","line":"}"},
{"lineNum":"   13","line":""},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2017-01-30 11:57:55", "instrumented" : 5, "covered" : 4,};
var merged_data = [];
[developer@centos7-xfce bob]$ 
```

You can see that `first/` is correct (4 lines, all covered) but the `third/kcov-merged/` result shows line 7 uncovered.

I noticed another odd thing that may be related: `first/index.json` shows `"covered_lines":"4","uncovered_lines":"3"`, even though `first/a.out/index.json` correctly shows `"covered_lines":"4","uncovered_lines":"0"`.

**Comment by SimonKagstrom** [comment]
I believe this is because the merge-reporter is created with a dummy filter (see src/main.cc). This is because normally you don't want to use the same exclusion pattern (for files) for the merged reports, but it also affects the line-matcher.

I'll check for a fix tonight.

**Comment by kswmsw** [comment]
Ah, OK. I got as far as noticing that runLineFilters is never called from merge-file-parser.cc, but hadn't figured out the reason. Thanks again for looking into this, I really appreciate it.

**Comment by SimonKagstrom** [comment]
I think the easy fix is just to move the implementation (in filter.cc) to the DummyFilter, and inherit the "normal" one from that. Then probably DummyFilter should be renamed BasicFilter or something like that.

**Comment by SimonKagstrom** [comment]
Fixed again with  87ea8b0 for merge-mode, thanks for the detailed reports!

**Comment by kswmsw** [comment]
Thanks! Reports for files are now correct, but there's still an issue with the toplevel index.json. After running `kcov first a.out` on the hello example:
```
$ cat first/index.json 
var data = {files:[
{"link":"a.out/index.html","title":"a.out","summary_name":"a.out","covered_class":"linePartCov","covered":"57.1","covered_lines":"4","uncovered_lines":"3","total_lines" : "7"},
], merged_files:[]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "a.out", "date" : "2017-01-30 16:06:52", "instrumented" : 7, "covered" : 4,};
```
which is wrong (somehow `uncovered_lines` is 3 not 0), but the next level down is correct:
```
$ cat first/a.out/index.json 
var data = {files:[
{"link":"hello.c.3c6dbdb9.html","title":"hello.c","summary_name":"[...]/bob/hello.c","covered_class":"lineCov","covered":"100.0","covered_lines":"4","uncovered_lines":"0","total_lines" : "4"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "a.out", "date" : "2017-01-30 16:06:52", "instrumented" : 4, "covered" : 4,};
var merged_data = [];
```

**Comment by SimonKagstrom** [comment]
Man, I'm beginning to regret the merge feature :-)

**Comment by SimonKagstrom** [comment]
Global index fixed in cb43e13!

**Comment by kswmsw** [comment]
Woot!! 100% coverage, thank you very much! This will make a big difference to our development process. Thank you for taking the time to address it!

**Comment by orium** [comment]
@SimonKagstrom Do you have an estimation date for a kcov release including this feature?

**Comment by SimonKagstrom** [comment]
Well, I'm still working on the system mode stuff, which I believe will take
a few weeks more at least. It's also vacation time now, so I'm rarely by
the computer, which hampers progress :-)

If its for Travis, probably you can checkout a git sha1 with the feature
included. Master should also be pretty stable, I do most development in
branches.

On Jul 20, 2017 13:24, "Diogo Sousa" <notifications@github.com> wrote:

@SimonKagstrom <https://github.com/simonkagstrom> Do you have an estimation
date for a kcov release including this feature?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SimonKagstrom/kcov/issues/180#issuecomment-316674925>,
or mute the thread
