### ISSUE TITLE
bash: No such file or directory

### ISSUE THREAD

**Issue by neg** [SimonKagstrom/kcov#68]
Hi, trying out the fix in #51 and it started out promising. But hit a odd glitch:

foo.sh
```bash
#!/bin/bash

echo "foo pre"
./bar.sh
echo "foo post"
```

bar.sh
```bash
#!/bin/bash

# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

echo "bar"
```
```shell
$ kcov tmpout ./foo.sh
foo pre
/bin/bash: : No such file or directory
foo post
```

```shell
 $ ./foo.sh
foo pre
bar
foo post
```

If I in bar.sh remove one of the comments or make the comments shorter it works as intended. I'm using 2ec9f01.

**Comment by SimonKagstrom** [comment]
Yes, I also noticed that it's unreliable. It works fine in my Fedora installation, but not under Ubuntu 14.04, and I suspect some memory overwrite or similar.

I'm working on a better fix for Issue #51, so we'll see if it fixes this problem as well.

**Comment by SimonKagstrom** [comment]
I've pushed a fix to Issue #51 that seems to work better on my Ubuntu computer at least.

**Comment by neg** [comment]
Tried with 0bd8bb1 and still have the same issue unfortunately. Running on RHEL 6.6 over here.

**Comment by SimonKagstrom** [comment]
OK, too bad. I can't reproduce this with your scripts. Just to check: Did this work with earlier kcovs (i.e., before the issue #51 fix)?

**Comment by neg** [comment]
It works fine using afe5793 (the commit before the first #51 commit)

**Comment by neg** [comment]
There is something fishy with the preloader I think, played around a bit with strace and found this:


When foo.bar is executed:
```
execve("/bin/bash", ["/bin/bash", "-x", "foo.sh"], [/* 111 vars */] <unfinished ...>

...

open("tmpa/bash-helper.sh", O_RDONLY|O_LARGEFILE) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=36, ...}) = 0
read(3, "#!/bin/sh\n\n# Turn on tracing\nset"..., 36) = 36 
close(3)                          = 0  
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
fstat64(2, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb73bf000
write(2, "kcov@tmpa/bash-helper.sh@4@set -"..., 34) = 34 
<... read resumed> "kcov@tmpa/bash-helper.sh@4@set -"..., 4096) = 34 
open("foo.sh", O_RDONLY|O_LARGEFILE <unfinished ...> 
getcwd( <unfinished ...> 
```

But when bar.sh is to be executed (called from foo.sh):
```
execve("/bin/bash", ["/bin/bash", "", "./bar.sh", "./bar.sh"], [/* 110 vars */]) = 0

...

open("tmpa/bash-helper.sh", O_RDONLY|O_LARGEFILE) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=36, ...}) = 0
read(3, "#!/bin/sh\n\n# Turn on tracing\nset"..., 36) = 36 
close(3)                          = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
open("", O_RDONLY|O_LARGEFILE)    = -1 ENOENT (No such file or directory)
stat64(".", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat64("/usr/local/bin/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat64("/usr/bin/", {st_mode=S_IFDIR|0755, st_size=77824, ...}) = 0
stat64("/bin/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat64("/usr/local/sbin/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat64("/usr/sbin/", {st_mode=S_IFDIR|0555, st_size=16384, ...}) = 0
stat64("/sbin/", {st_mode=S_IFDIR|0555, st_size=12288, ...}) = 0
fstat64(2, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7457000
write(2, "/bin/bash: : No such file or dir"..., 39) = 39 
<... read resumed> "/bin/bash: : No such file or dir"..., 4096) = 39 
exit_group(127)                   = ?
write(2, "/bin/bash: : No such file or dir"..., 39) = 39 
```

**Comment by SimonKagstrom** [comment]
OK, so the arguments are not propagated to argv via the preloaded library.

Even the first commit (which uses a stack-allocated argv) worked fine in my Fedora 21 installation, but broke in Ubuntu 12.04 (travis). The second commit instead heap-allocates argv and arguments, but apparently that doesn't quite cut it either. I understand that execve is slightly special though, and I guess the heap might be re-initialized with the new executable.

**Comment by SimonKagstrom** [comment]
I added a --bash-handle-sh-invocation option to optionally turn on the LD_PRELOAD hack, but for now it's default off.
