### ISSUE TITLE
kcov: Another report coloring issue

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [SimonKagstrom/kcov#70]
I have a number of different versions of a test script. For the first
````
#!/bin/bash
var=(c)
test ${#var[*]} -gt 2 -o \
     "${var[$((${#var[*]} - 1))]}" != "c" ||
    {
    echo Some line
    }
echo Something else
````
the report correctly shows 100% coverage, but nothing after line 3 is colored. If I join line 3 and line 4, all subsequent lines are covered. 

If I change it to this:
````
#!/bin/bash
var=(c)
test ${#var[*]} -gt 2 -o \
     "b" != "c" ||
    {
    echo Some line
    }
echo Something else
````
the report shows 60% coverage, all lines are colored, and 4 and 6 are red, which looks correct.

This change
````
#!/bin/bash
var=(c)
test 1 -gt 2 -o \
     "${var[$((${#var[*]} - 1))]}" != "c" ||
    {
    echo Some line
    }
echo Something else
````
produces 100% coverage, but all lines are colored except for line 4. If I join lines 3 and 4 in this example, it sitll reports 100% but now only line 2 is colored (green.) 

I've tried other combinations, but I'm not sure exactly what's causing it. I suspect the ${#var} syntax, but I'm not sure.

**Comment by SimonKagstrom** [comment]
As you probably suspected as well, it's likely an issue with the backslash for continue-on-next-line.

**Comment by SimonKagstrom** [comment]
Actually it wasn't - it was a problem with $# and ${#var} expansion! Fixed in 2cea67f.

**Comment by Mark-E-Hamilton** [comment]
Thanks for the response. When I test the last case (with the continuation escape) line 4 still doesn't show as green. Is that due to the short-circut evaulation of the expression?

**Comment by SimonKagstrom** [comment]
Sorry for not responding to this, I've had some time off kcov for a while.

Anyway, it's sort of a conscious decision to mark the next line as non-code. When running with bash -x (without PS4), it will actually process the backslash, so the output will look something like

```
+ var=(c)
+ test 1 -gt 2 -o c '!=' c
+ echo 'Some line'
```

and when looking at LINENO, only the first line will be marked. I decided at some point to handle backslashes by simply going for what LINENO says, and mark the next line as non-code. I suppose another way could be to have it piggy-back on the line next to it, so that if that's covered, the backslashed line will also be and vice versa.

That is slightly more complex to implement though. I can write a new issue to track that particular problem, but will close this one again.

**Comment by Mark-E-Hamilton** [comment]
That's okay. We all need some time off, especially from things that 
cause stress with no remuneration. ;)

IAE, that last was more of an observation on my part. I'm good with it.

I'm actually backing off of pushing forward with kcov myself for a 
little while. Other commitments are requiring more of my time. I'm not 
dropping it, but I might be slower with issues than I have been for the 
past few weeks.

Thanks.

-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666
